### ISSUE TITLE
Permission to push 'changes/create branches' denied

### ISSUE THREAD

**Issue by hsanchez** [aas-integration/clusterer#1]
I am trying to publish a branch that contains my changes but I cannot (see error messages below):

'remote: Permission to aas-integration/clusterer.git denied to hsanchez.
fatal: unable to access 'https://github.com/aas-integration/clusterer.git/': The requested URL returned error: 403'

@martinschaef can you add me as a collaborator of this repo?

**Comment by martinschaef** [comment]
Yep ... done
