### ISSUE TITLE
No word to field mapping produced on corpus

### ISSUE THREAD

**Issue by martinschaef** [aas-integration/clusterer#9]
I get an empty word to field mapping on the corpus :(
```json
{
  "mappings": [
  ]
}
```

Looks like the introspector stuff is not running when I start it from a Jar ... I assume that it doesn't find its way into the jar ...

**Comment by martinschaef** [comment]
Ok, something goes wrong when packing introspector into a jar. If I run the same command from eclipse, it runs smooth but if I run it from the jar it only produces an empty map. @hsanchez do you rely on resource that doesn't make it into the Jar?

**Comment by hsanchez** [comment]
There is resource that does not make it into the jar. A txt file for the introspector spell checker: big.txt.

**Comment by martinschaef** [comment]
ok, I'll squeeze that in.

**Comment by martinschaef** [comment]
Hmm ... added it to the jar but doesn't change things ... where is that being loaded? Couldn't find a reference to it in the code.

**Comment by hsanchez** [comment]
Hmm. It should work. Try this: Don't include in the jar, but place it where the the produced jar is. Then test it again.

**Comment by martinschaef** [comment]
Nope ... anyway, since I don't see who loads the file (there is no line searching for it), I consider this your ball. 
For now, I produced the output for the corpus from eclipse and sent it around, so it's not urgent. 
But it has to be fixed latest next week.

**Comment by martinschaef** [comment]
:1st_place_medal:
